# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 4dfb164cc07c
Revises: 95d75e1d8f64
Create Date: 2024-09-25 11:08:52.473111

"""

# revision identifiers, used by Alembic.
revision = '4dfb164cc07c'
down_revision = '95d75e1d8f64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('saved_query', sa.Column('dqc_id', sa.Integer(), nullable=True))

    op.create_unique_constraint('uq_saved_query_dqc_id', 'saved_query', ['dqc_id'])
    op.create_unique_constraint('uq_saved_query_label', 'saved_query', ['label'])
    
    # ### end Alembic commands ###


def downgrade():
   
    op.drop_constraint('uq_saved_query_label', 'saved_query', type_='unique')
    op.drop_constraint('uq_saved_query_dqc_id', 'saved_query', type_='unique')

    op.drop_column('saved_query', 'dqc_id')
   
    # ### end Alembic commands ###
